# Generated by Django 4.0.3 on 2022-03-20 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('biography', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('ISBN', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('title', models.TextField(default='')),
                ('summary', models.CharField(default='', max_length=255)),
                ('numberOfPages', models.IntegerField(default=0)),
                ('language', models.CharField(default='', max_length=50)),
                ('image', models.TextField(default='', max_length=255)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.author')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('description', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('address', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='BookItem',
            fields=[
                ('barcode', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('price', models.FloatField(max_length=50)),
                ('discount', models.CharField(max_length=50)),
                ('inventory', models.IntegerField(default=0)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.book')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='categoryBook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.categorybook'),
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.publisher'),
        ),
    ]
